Example/android/app/src/main/res/values/colors.xml, README.md, android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java, index.d.ts, index.js
- Better document and demonstrate the best practices for styling on Android
- Eliminate confusion and help users best style Android SDK via React Native
- Legacy `Styling` code for Android didn't work as expected (specifically for the SeekBar)
- No
- No
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/12)
=> Update: Add comments regarding styling for Android

android/src/main/java/com/jwplayer/rnjwplayer/Util.java
- Fixes potential crashes when not specifying the `default` prop on `sources` and `tracks` objects
- To fix crashes
- No
- No
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/10)
=> Fix for safe parsing default value for tracks and sources

android/src/main/java/com/jwplayer/rnjwplayer/Util.java, index.d.ts, index.js
- Start parsing for different tracks types from the `tracks` prop
- When using legacy props, there was no way to load in anything other than caption tracks
- No, but since iOS doesn't require `kind`, we cannot make it required. This causes the need for the check if `kind` key exists. 
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/17)
=> Fix all tracks are being marked captions

android/src/main/java/com/jwplayer/rnjwplayer/Util.java
- Put the instantiation of a variable before it's usage
- Broken Android building
- no
- no
N/A: Non-issue bug fix
=> ADHOC: clean up a bad merge causing Android build bug

README.md
Adds links to the JW Docs for the mobile SDKs.
Developers who come to the RN bridge from the RN side, rather than the native side, will not automatically know where to look for definitive configuration info, such as the minimum OS versions and the like.
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/###)
=> Updates Readme - adds links to JW Docs

Example/ios/Podfile.lock, Example/ios/RNJWPlayer.xcodeproj/project.pbxproj, RNJWPlayer.podspec
* Changes the podspec dependency versions to those that support privacy manifests:
* JWP iOS SDK 4.19.0+
* IMA SDK 3.22.0
* Cast SDK 4.8.1
* Updates pods for example project.
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/###)
=> Updates iOS dependency to adopt privacy manifests

package.json
Makes badge-maker a dev dependency.
Reduces the number of dependencies added when installing the library.
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/37)
=> chore: badge-maker as dev dep

index.js, package.json, yarn.lock
Reduces the bundle size of the package by replacing lodash with `lodash.isequalwith`.
Lodash is among the largest dependencies in one representative app, this decreases the JavaScript bundle size by half a megabyte.
This should in theory work identically, but may be worth checking that the `shouldComponentUpdate` check functions the same.
No.
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/41)
=> feat: shrink bundle by replacing lodash with lodash.isequalwith

ios/RNJWPlayer/RNJWPlayerViewManager.m
Removes the cast methods from the list of methods exported to React Native on iOS when `USE_GOOGLE_CAST` is not enabled.
iOS apps without this crash on React Native's new architecture after being built with Google Cast support, because otherwise the code tries to reference missing methods.
No.
No.
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/48)
=> fix: prevent iOS crash when Google Cast is not enabled and React Native's new architecture is

Example/android/app/src/main/AndroidManifest.xml, Example/android/app/src/main/java/com/rnjwplayer/MainActivity.java, Example/yarn.lock, android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java
- Enhance PiP implementation
- Fix Toolbar displaying in PiP issue in Example
- Slightly resolve the PiP issue where player isn't centered
- PiP on Android isn't working well
- Example app wasn't setup well for PiP
- Test implementation with the following config
```
let jwConfig = {
"title": "Single Inline Linear Preroll",
"playlist": [
{
"title": "Single Inline Linear Preroll",
"file": "https://content.bitsontherun.com/videos/q1fx20VZ-52qL9xLP.mp4"
}
],
"pipEnabled":true
}
```
- Hiccup when switching into PiP... React Native seems to want to reshow the toolbar so I had to take some workaround steps to ensure the Player is rendered in frame of PiP. 
- No
- Internal JWP ticket
=> Implement PiP receiver. Refactor Example to better implement PiP. Fix view display issue in PiP

README.md, ios/RNJWPlayer/RNJWPlayerView.swift
- Make iOS PiP work out of the box
- Better define requirements for PiP
- Safer handling of `category` and `categoryOptions`
- Make iOS PiP work again
- no
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/70)
=> [BUG] PiP not working on iOS

index.d.ts
- Add typedef for a few non parsing props in `JwConfig`
- Missing typedefs
- No
- No
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/52)
=> Add playerInModal to type def for JwConfig

android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java, index.d.ts, ios/RNJWPlayer/RNJWPlayerView.swift, ios/RNJWPlayer/RNJWPlayerViewController.swift
- Ensure warning and errors are the same for both platforms
- Ensure native events are passed to react side
- Errors weren't being surfaced (sometimes)
- Info in warnings and errors was missing information
- no
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/63)
=> [BUG] Error and warning standardization

ios/RNJWPlayer/RNJWPlayerViewManager.swift
Switches setCurrentCaptions to use setCaptionTrack(index:) instead of currentCaptionsTrack = index. This is what JWPlayer’s docs say to use. https://sdk.jwplayer.com/ios/v4/reference/Protocols/JWPlayerProtocol.html#/c:@M@JWPlayerKit@objc(pl)JWPlayerProtocol(im)setCaptionTrackWithIndex:error:
The old way didn’t match their official docs, so this should be more correct and less likely to break.
Make sure try is used right for the setCaptionTrack method, since it can throw errors.
Nope.
=> [bug]Updates ios setCurrentCaptions to implement correctly

android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerModule.java, android/src/main/java/com/jwplayer/rnjwplayer/Util.java, index.d.ts, ios/RNJWPlayer/RNJWPlayerViewManager.m, ios/RNJWPlayer/RNJWPlayerViewManager.swift
- Update typing for `loadPlaylist`
- Support `JwPlaylistItem` and string for URL
- Update Native code to support above
- Places TODO for when iOS exposes more options in the `JWJSONParser`
- Fix TS definitions
- Allow more flexibility in the `loadPlaylist` method
- no
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/56)
=> [Improvement] Modernize loadPlaylist function with types and logic

Example/package.json, android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerModule.java, android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java
- Adds check if background service is running before attempting to bind it to activity
- Adds warning message in Android for when above happens
- Adds comments explaining why not to do this
- Fatal crash thrown when developer has two players with background audio enabled (this is not a valid use case in the current configuration)
- no
- no 
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/77)
=> [BUG] app crashes when attempting to play a second video while another is playing

ios/RNJWPlayer/RNJWPlayerView.swift
- Fix broken RNJWPlayerView.swift
- We removed the wrong override
- Needed to keep `jwplayerContentIsBuffering` for `JWPlayerDelegate`
- no
- no
ADHOC
=> add in required override for JWPlayerDelegate

index.js
- Stop calling `.quite` when building a new player
- Adding a new player can disrupt playback for already attached players
- Consider the issue on iOS when players are destroyed individually and what can happen to the audio session.
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/71)
=> [BUG] Take the quite call out of player constructor

android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java, ios/RNJWPlayer/RNJWPlayerViewManager.swift
- Add missing listener for Android tracks callbacks
- Modernize getAudioTracks for iOS v4 objects
- Android onAudioTracks not firing
- getAudioTracks broken on iOS
- no
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/65)
=> [BUG] onAudioTracks and getAudioTracks not working

ios/RNJWPlayer/RNJWPlayerView.swift, ios/RNJWPlayer/RNJWPlayerViewController.swift
This fixes the onAdEvent in the native iOS codebase. It does this by adding .description to the argument so that a string is passed to the RN wrapper. Example:
`onAdEvent?(["client": event.client.description, "type": event.type.description])`
When logging the onAdEvent on an iOS device the event was logging null for `client` and `type`. For example:
`onAdEvent {"client": null, "target": 187, "type": null}`
After the fix, the log now looks like this:
`onAdEvent {"client": "googima", "target": 187, "type": "request"}`
No
No
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/###)
=> Added .description so onAdEvent returns a string

android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java, android/src/main/java/com/jwplayer/rnjwplayer/Util.java, index.d.ts, ios/RNJWPlayer/RNJWPlayerView.swift, ios/RNJWPlayer/RNJWPlayerViewController.swift
PR updates the JS side `onAdEvent` callback by instead using and passing the number representation of ad client and ad event/type from the native side on both platforms ( IOS/Android ) . 
With this PR, we can be able to consistently derive on both platforms the ad client and event type using these available constants on the JS side:
1. Ad Event Types - https://github.com/jwplayer/jwplayer-react-native/blob/master/index.js#L40
2. Ad Clients - https://github.com/jwplayer/jwplayer-react-native/blob/master/index.js#L72
Example: 
```javascript
onAdEvent={({ nativeEvent }) => {
const { JWAdEventTypeComplete, JWAdEventTypeImpression, JWAdEventTypePlay } = JWPlayerAdEvents;
const isAdImpression = nativeEvent.type === JWAdEventTypeImpression;
const isAdPlaying = nativeEvent.type === …
```
=> Use number representation of ad event type and client.

android/src/main/java/com/jwplayer/rnjwplayer/RNJWPlayerView.java
- Ensure player and player view are aware of current lifecycle state
- Ads were not playing due to lifecycle bing out of sync with actual state
- No
- Using `backgroundAudioEnabled` was a workaround but not a viable long-term solution. 
- No
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/117)
=> [Android] Sync lifecycle of view with player

index.d.ts, index.js, ios/RNJWPlayer/RNJWPlayerViewManager.m, ios/RNJWPlayer/RNJWPlayerViewManager.swift
- Fix loadPlaylist on iOS
- Expose loadPlaylistWithUrl in JS
- Possible fatal crash on older ReactNative
- Type mismatch non-fatal issue
- no
- no
[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/115)
=> Fix loadPlaylist and fully expose loadPlaylistWithUrl

android/build.gradle
- Upgrade to JWP Android 4.20.0
- Upgrade to JWP Android 4.20.0
- Fix a bug with related configs / thumbnails / and other HTTP requests failing after initial load
- no
- no
- https://github.com/jwplayer/jwplayer-react-native/issues/123
- https://github.com/jwplayer/jwplayer-react-native/issues/67
- Fixes issues (that I cannot find now) around any HTTP request failing after initial setup
=> [Task] Upgrade Android to JWP SDK 4.20.0
